name: "Terraform Destroy"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DESTROY" to confirm'
        required: true
        default: 'NO'

jobs:
  destroy:
    name: "Destroy Infrastructure"
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Automatically kills the job if it gets stuck
    # Only run if the user typed "DESTROY" in the manual prompt
    if: github.event.inputs.confirm == 'DESTROY'
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve