name: "Terraform Plan & Apply"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "APPLY" to confirm'
        required: true
        default: 'NO'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Automatically kills the job if it gets stuck
    if: github.event.inputs.confirm == 'APPLY'
    defaults:
      run:
        working-directory: ./terraform
    env:
      # Map your secrets to environment variables
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="variable.tfvars"
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="variable.tfvars"