name: Vault Integration

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  vault:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get OIDC Token
        id: oidc
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com" | jq -r '.value')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Login to Vault
        id: vault-login
        run: |
          RESPONSE=$(curl --request POST \
            --data "{\"role\":\"github-actions\",\"jwt\":\"$TOKEN\"}" \
            http://<YOUR-VAULT-IP>:8200/v1/auth/oidc/login)

          VAULT_TOKEN=$(echo $RESPONSE | jq -r '.auth.client_token')
          echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV

      - name: Read Secret from Vault
        run: |
          SECRET=$(curl \
            --header "X-Vault-Token: $VAULT_TOKEN" \
            http://<YOUR-VAULT-IP>:8200/v1/secret/data/github/token \
            | jq -r '.data.data.value')

          echo "Secret is: $SECRET"